### PR TITLE
Polish Card Section

### PR DESCRIPTION
**Pull request by PlabanKr**
I have tried to give the cards a new polish look with material ui.

### CODE REVIEW

**Comment by PlabanKr** [comment]
@guptasajal411 Hello, I've tried to polish the look of cards using `material-ui`. Sorry I didn't created any issue before doing this. Can you check the pull request and give your opinion on it?

**Comment by guptasajal411** [comment]
Thanks for opening a PR in VIT Links! I will review the changes

**Review by guptasajal411 — APPROVED** [review]
LGTM 💯

**Comment by guptasajal411** [comment]
Pull request is merged 🥳 You can view the updated deployment  here: https://vit-links-frontend.vercel.app
Sorry for late response from my side

**Comment by PlabanKr** [comment]
Thank you for accepting my pull request!! 🥳🥳
Happy Coding 🥳🥳

**Pull request merged**
